
name: Linux build by nuitka

on:
 push:
   branches:
     - master
   paths-ignore:
     - "build\&setup_scripts/**"
jobs:
 build:
   runs-on: ubuntu-18-04
   steps:
     - run: sh build\&setup_scripts/build4ubuntu_host.sh
     - run: tar -zcvf build.tar.gz build/app.dist
     - uses: actions/upload-artifact@v1
        with:
          name: app.tar.gz
          path: build.tar.gz
