name: PyInstaller Linux

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - name: Installing PyInstaller
      run: |
        pip install pyinstaller
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python build\&setup_scripts/run_me.py
   
    - name: build with pyinstaller
      run: |
        pyinstaller app.py

    - name: ZIP Files
      run: |
        zip -r pyinstaller_build.zip dist 
      
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          ls /home/runner && echo 777 && ls /home/runner/work/s2txt/s2txt
        uses: actions/checkout@v2
      - name: Publish Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/pyinstaller_build.zip
          asset_name: pyinstaller_build.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
        
