name: PyInstaller Linux

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - name: Installing PyInstaller
      run: |
        pip install pyinstaller
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python build\&setup_scripts/run_me.py
   
    - name: build with pyinstaller
      run: |
        pyinstaller app.py

    - name: ZIP Files
      run: |
        zip -r pyinstaller_build.zip dist 
      
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pipe-cd/actions-gh-release@v2.2.0
        with:
          release_file: 'pyinstaller_build.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
    
